### ISSUE TITLE
Выбрать сервис для временной почты

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/subscription-service#1]
Нужено выбрать сервися для автоматического осоздания почты с возможностью логиниться под уже созданной почтой. Это необходимо для регистрации аккаунта через [Adobe API](https://github.com/Adobe-for-Alex/adobe-api) и возможность подтверждать личность (на почту высылается код)

**Comment by a9ek0** [comment]
## Выбранное решение

Было решено использовать сервис [mail.tm](https://mail.tm/), так как он соответствует следующим требованиям:

- Имеется возможность сохранять созданный почтовый ящик и входить в него для получения сообщений.
- Доступно API для взаимодействия.

## Документация

Официальная документация для интеграции с API mail.tm:

- [Mail.tm API Documentation](https://api.mail.tm/)
- [Mail.tm Docs](https://docs.mail.tm/)

**Comment by Chamber6821** [comment]
Сколько толго существует почта в этом сервисе? Нам нужно в районе 14 дней

**Comment by a9ek0** [comment]
Почта действительна до момента ее удаления. 
**Источник:** [Mail.tm FAQ](https://mail.tm/ru/faq/#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D1%80%D0%BE%D0%B4%D0%BB%D0%B8%D1%82%D1%8C%20%D0%B2%D1%80%D0%B5%D0%BC%D1%8F%20%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8%20%D0%BF%D0%BE%D1%87%D1%82%D1%8B%3F)
