### ISSUE TITLE
Интегрировать с Docker

### ISSUE THREAD

**Issue by Chamber6821** [Adobe-for-Alex/subscription-service#3]
Нужно написать Dockerfile из конторого будет собираться образ микросервиса.
Нужно написать docker-compose.yml для разворачивания микросервиса с его базой данных для тестирования, так же будет выступать в роли примера использования

**Comment by Chamber6821** [comment]
Этот Issue зависит от #2

**Comment by Chamber6821** [comment]
Дедлайн по этой задаче: 25.10 12:00

**Comment by Chamber6821** [comment]
[Пример Dockerfile](https://github.com/Chamber6821/kosox-web/blob/master/Dockerfile)

[Пример docker-compose.yml](https://github.com/Chamber6821/kosox-entry/blob/master/docker-compose.yml)

**Comment by Chamber6821** [comment]
@a9ek0 этот Issue отмечен как `dependent`, а значит его нельзя выполнить без выполнения какого-то другого Issue. Поэтому доведи сначала #4 до конца

**Comment by a9ek0** [comment]
@Chamber6821 Я сделал, за исключением папки workflows. Я удалю её в следующем коммите. (#5)
